/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerIdRouteImport } from './routes/customer.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIdRoute = CustomerIdRouteImport.update({
  id: '/customer/$id',
  path: '/customer/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/customers': typeof CustomersRoute
  '/insights': typeof InsightsRoute
  '/memories': typeof MemoriesRoute
  '/settings': typeof SettingsRoute
  '/customer/$id': typeof CustomerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/customers': typeof CustomersRoute
  '/insights': typeof InsightsRoute
  '/memories': typeof MemoriesRoute
  '/settings': typeof SettingsRoute
  '/customer/$id': typeof CustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/customers': typeof CustomersRoute
  '/insights': typeof InsightsRoute
  '/memories': typeof MemoriesRoute
  '/settings': typeof SettingsRoute
  '/customer/$id': typeof CustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversations'
    | '/customers'
    | '/insights'
    | '/memories'
    | '/settings'
    | '/customer/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversations'
    | '/customers'
    | '/insights'
    | '/memories'
    | '/settings'
    | '/customer/$id'
  id:
    | '__root__'
    | '/'
    | '/conversations'
    | '/customers'
    | '/insights'
    | '/memories'
    | '/settings'
    | '/customer/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversationsRoute: typeof ConversationsRoute
  CustomersRoute: typeof CustomersRoute
  InsightsRoute: typeof InsightsRoute
  MemoriesRoute: typeof MemoriesRoute
  SettingsRoute: typeof SettingsRoute
  CustomerIdRoute: typeof CustomerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/$id': {
      id: '/customer/$id'
      path: '/customer/$id'
      fullPath: '/customer/$id'
      preLoaderRoute: typeof CustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversationsRoute: ConversationsRoute,
  CustomersRoute: CustomersRoute,
  InsightsRoute: InsightsRoute,
  MemoriesRoute: MemoriesRoute,
  SettingsRoute: SettingsRoute,
  CustomerIdRoute: CustomerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
